export const viewportWidth = window.innerWidth;

export const surpriseMePrompts = [
  "An artistic render of a fox made of fire",
  "an armchair in the shape of an avocado",
  "a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers",
  "teddy bears shopping for groceries in Japan, ukiyo-e",
  "an oil painting by Matisse of a humanoid robot playing chess",
  "panda mad scientist mixing sparkling chemicals, digital art",
  "Ultrawide, « lake of Annecy » with golden ratio style, 4K , foreground is prairie, light is Golden hour, sky with red Clouds, ultrarealistic, CinémaScope, ultra wide format, ratio 16/9, 1/1000 sec, maximum resolution, Sharp details",
  "3D render of a cute tropical fish in an aquarium on a dark blue background, digital art",
  "3D render of a floating futuristic castle in a clear sky, digital art",
  "photo of a sad t-rex looking at the stars",
  "a stained glass window depicting a hamburger and french fries",
  "a pencil and watercolor drawing of a bright city in the future with flying cars",
  "a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art",
  "a fortune-telling shiba inu reading your fate in a giant hamburger, digital art",
  "a big large happy kawaii fluffy cutest baby Shiba-inu puppy wearing kimono enjoy shopping in a futuristic abandoned city, anime movie, IMAX, cinematic lighting, only in cinema, Makoto Shinkai",
  "an oil pastel drawing of an annoyed cat in a spaceship",
  "a painting of a fox in the style of Starry Night",
  "studio photography set of high detail irregular marble stones with gold lines stacked in impossible balance, perfect composition, cinematic light photo studio, beige color scheme, indirect lighting, 8k, elegant and luxury style",
  "a dragon rising from a volcano, ready to attack a futuristic city that lies next to a mountain, digital art",
  "A synthwave style sunset above the reflecting water of the sea, digital art",
  "Two futuristic towers with a skybridge covered in lush foliage, digital art",
  "A 3D render of a rainbow colored hot air balloon flying above a reflective lake",
  "a hyper realistic rilakkuma enjoying an icecream in the snow",
  "Oil painting, highly detailed, the landscape of a blue full moon's night, panned out view of the character, visible full body, Hyperrealist grey-skinned menacing muscular white werewolf in a battle stance, wearing red clothes with silver filigree details, standing at the top of a lush hill looking at the horizon in a dark enchanted forest of bioluminescent trees and glowing plants, UHD, HDR, 8K",
  "A photo of a Samoyed dog with its tongue out hugging a white Siamese cat",
  "A photo of a white fur monster standing in a purple room",
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  "hot dark hair girl,  looking at viewer, portrait, photography, detailed skin, realistic, photo-realistic, 8k, highly detailed, full length frame, piercing, diffused soft lighting, shallow depth of field, sharp focus, hyperrealism, cinematic lighting  ",
  "high res 3d ultra high definition roman sculptures dancing under the pillars of creation",
  "A realistic photograph of a young woman with blue eyes and blonde hair",
  "A greeting cat, Vector Illustation, line stamp, kawaii",
  "Spongebob Squarepants in the Blair Witch Project",
  "A velociraptor working at a hotdog stand, lomography",
  "A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens",
  "A BBQ that is alive, in the style of a Pixar animated movie",
  "A futuristic cyborg dance club, neon lights",
  "A photo of Metro Manila as a walkable city with lots of green spaces and a beautiful overground MRT system",
  "A hamburger in the shape of a Rubik’s cube, professional food photography",
  "A Synthwave Hedgehog, Blade Runner Cyberpunk",
  "An astronaut encountering an alien life form on a distant planet, photography",
  "A dutch masters painting of a blue jay with a gold earring",
  "A Man falling in Love with his Computer, digital art",
  "A photograph of a cyborg exploring Tokyo at night, lomography",
  "Dracula walking down the street of New York City in the 1920s, black and white photography",
  "cutie fluffy creature movie star people, digital art, 3 d, octave render, masterpiece, mega detailed, pixar, disney, vivid illustration, cartoon, fantasy, by george stubbs, artgerm, in the style of ghibli kazuo oga, pastel fur ",
  "A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm",
  "A Space Shuttle flying above Cape Town, digital art",
];
